### PR TITLE
implement fractional times from 2076-2

### LINKED ISSUE #69: Support fractional time format
In [2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf). time format now includes this fractional based format: hh:mm:ss.xxxxxSyyyyy (where xxxxx & yyyyy the numerator and denominator of a fraction, e.g. 12000S48000).

### From the standard

>5.11 Time parameters format
>
>Time-related parameters shall have the format of ‘hh:mm:ss.zzzzz’ or ‘hh:mm:ss.zzzzzSfffff’.
>
>‘hh:mm:ss.zzzzz’ indicates hours, minutes, seconds. The number of decimal places for the seconds should be a minimum of 5. There should be enough decimal places used for sample-accurate timing. For example, 01:34:16.25000.
>
>‘hh:mm:ss.zzzzzSfffff’ indicates hours, minutes, seconds with a fractional representation  of  sub-seconds.  The  zzzzz  digits  represent  the  numerator  of  a  fraction,  and  the  fffff  digits  represent  the denominator. The number of digits for zzzzz and fffff should be at least five each. This format allows a sample-based representation oftime to be used, where zzzzz is the number of samples, and fffff is the sample-rate. The value of zzzzz should be less than fffff to ensure a fraction less than one. Both values   should   not   be   negative,   and   fffff   should   be   greater   than   zero. For example, 01:34:16.12000S48000 is the same as 01:34:16.25000.

### Definition of done
For all time based parameters in libadm we are able to:
- [ ] correctly parse a fractional format time parameter from XML, then write it back again without modification. Given a valid timestamp, the same timestamp should be written in the same format.
- [ ] create both ns and fractional time parameters using the libadm API
- [ ] modify an existing time based parameter, changing representation if required
- [ ] correctly write newly created or modified time based parameters to XML in the chosen format
- [ ] continue to parse and write ns timestamps correctly
- [ ] provide useful feedback when invalid timestamps of either representation are encountered

### PR DESCRIPTION
**Pull request by tomjnixon**
Closes #69

### CODE REVIEW

**Comment by tomjnixon** [comment]
Things to address:
- [ ] test exception(s)
- [ ] test extra characters at end of string when parsing
- [ ] check constraints on fractional part when parsing (+ve denominator, numerator < denominator)
- [ ] check whether overloading `operator<<` in `std` makes sense / is necessary
- [ ] turn comments into sections in tests

**Comment by benjamin-weiss** [comment]
If you are already changing the standard to C++14 I would consider changing it to C++17. It should then be quite easy to get rid of the boost dependency.

**Comment by benjamin-weiss** [comment]
I haven't thought this trough, but couldn't you just use custom std::chrono types instead of defining your own class. 

template<
    class Rep, 
    class Period = std::ratio<1> 
> class duration;

I suppose you would just have to use the std::ratio which corresponds to the used sample rate or not?

**Comment by tomjnixon** [comment]
Thanks for having a look.

The issue with using `std::chrono::duration` is that the ratio is a template parameter, but we want to support arbitrary denominators at run-time. It would probably be handy to have a (templated) method in `Time` to convert to durations with arbitrary ratios, though.

**Comment by benjamin-weiss** [comment]
Why do you want to support arbitrary denominators? I know in theory (and according to BS.2076-2) it could be any value greater than zero. But in practice? Shouldn't that be just the list of common sample and frame rates? Or am I missing a use-case?

**Comment by tomjnixon** [comment]
For me, the hard requirements are:

- support for common fractional denominators (and decimal) without ever rounding
- ability to set the representation when generating files (i.e. the user decides between fractional/decimal and can set the denominator)

The first is there because rounding causes issues while rendering, and we want to be able to generate correct files where the end of one block lines up exactly with the next.

The second is so that if someone comes up with a profile that says "times must be represented as fractional with a denominator of 50", we can use libadm to generate compatible files.

I think those requirements lead to a design like this. Maybe it could be simpler for reading, but I think the complexity is necessary for writing, and it should be symmetrical. If you want to convert everything to a duration then you can still do that with this design (and the operations performed are going to be the same, it just takes slightly more storage).

**Pull request closed without merging**
