### PR TITLE
Auto base vector

### PR DESCRIPTION
**Pull request by tomjnixon**
add a vector type to the auto base thing, and write some tests

### CODE REVIEW

**Comment by tomjnixon** [comment]
looks like MSVC might need an explicit instantiation of a template class with exported methods in order to use inline methods defined in it, but gcc/clang doesn't. I wish this stuff was standardised!

**Comment by tomjnixon** [comment]
I didn't think properly about the exporting before writing this test. Some options to deal with this:
- don't bother testing this code directly, and rely on tests of the element types to catch issues
  - not ideal, as it makes developing new functionality a bit annoying, and the tests serve as a good example of how it should be used
- only enable these tests if `ADM_HIDE_INTERNAL_SYMBOLS` is not set
  - not built on CI, but these tests are more useful for development
- add something to `auto_base_tests.cpp` which disables `ADM_EXPORT` before the inclusion of `auto_base.hpp`
  - not nice, but reliable and simple

Thoughts?

**Comment by tomjnixon** [comment]
> Just to check I understand the issue - Is the problem that in the tests that we're using Parameter types that are declared outside of libadm (in the test executable) rather than within libadm, as would be the case for "real" usage?

Yeah, exactly. To get gcc/clang to export the template methods in the normal use they need to have an export tag, but that means that on windows in the tests they end up being declared `__declspec(dllimport)`, and that breaks because they are not defined in libadm.

**Comment by rsjtaylor** [comment]
The additional #define seems like a reasonable work-around to me. It's not really any less nice than having to define an export macro in the first place.

**Review by rsjtaylor — APPROVED** [review]

**Comment by tomjnixon** [comment]
thanks, merged.

**Pull request closed without merging**
