### PR TITLE
Implement fractional time from BS.2076-2

### LINKED ISSUE #69: Support fractional time format
In [2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf). time format now includes this fractional based format: hh:mm:ss.xxxxxSyyyyy (where xxxxx & yyyyy the numerator and denominator of a fraction, e.g. 12000S48000).

### From the standard

>5.11 Time parameters format
>
>Time-related parameters shall have the format of ‘hh:mm:ss.zzzzz’ or ‘hh:mm:ss.zzzzzSfffff’.
>
>‘hh:mm:ss.zzzzz’ indicates hours, minutes, seconds. The number of decimal places for the seconds should be a minimum of 5. There should be enough decimal places used for sample-accurate timing. For example, 01:34:16.25000.
>
>‘hh:mm:ss.zzzzzSfffff’ indicates hours, minutes, seconds with a fractional representation  of  sub-seconds.  The  zzzzz  digits  represent  the  numerator  of  a  fraction,  and  the  fffff  digits  represent  the denominator. The number of digits for zzzzz and fffff should be at least five each. This format allows a sample-based representation oftime to be used, where zzzzz is the number of samples, and fffff is the sample-rate. The value of zzzzz should be less than fffff to ensure a fraction less than one. Both values   should   not   be   negative,   and   fffff   should   be   greater   than   zero. For example, 01:34:16.12000S48000 is the same as 01:34:16.25000.

### Definition of done
For all time based parameters in libadm we are able to:
- [ ] correctly parse a fractional format time parameter from XML, then write it back again without modification. Given a valid timestamp, the same timestamp should be written in the same format.
- [ ] create both ns and fractional time parameters using the libadm API
- [ ] modify an existing time based parameter, changing representation if required
- [ ] correctly write newly created or modified time based parameters to XML in the chosen format
- [ ] continue to parse and write ns timestamps correctly
- [ ] provide useful feedback when invalid timestamps of either representation are encountered

### PR DESCRIPTION
**Pull request by tomjnixon**
This is a squashed version of #75 ; some of the discussion there is relevant.

The full history is on the feature_fractional_time_unsquashed branch.

Closes #69

### CODE REVIEW

**Review by firthm01 — APPROVED** [review]
This looks really nice. Apologies for the delay; I had a hunch that there may be issues around using mixed denominators but it looks to handle it well - seems that boost::rational still returns something sensible when doing arithmetic operations using lowest common divisor.
I did wonder if we could retain backwards compatibility in the public facing API for "get" on any time-related ADM parameters, but on reflection I think it's OK to break it in this case in order to keep a tidy, logical code base.

**Comment by firthm01** [comment]
I knew there was something else I wanted to mention; Is there a specific reason for the subtractTimes helper, rather than an operator overload in the Time class?

**Comment by tomjnixon** [comment]
> This looks really nice. Apologies for the delay; I had a hunch that there may be issues around using mixed denominators but it looks to handle it well - seems that boost::rational still returns something sensible when doing arithmetic operations using lowest common divisor.

Great, thanks; yeah, it does the right thing.

> I did wonder if we could retain backwards compatibility in the public facing API for "get" on any time-related ADM parameters, but on reflection I think it's OK to break it in this case in order to keep a tidy, logical code base.

It's a good idea; I'd rather not do this though because not all fractions can be represented as nanoseconds, so it's best if users are nudged to do the right thing.

> I knew there was something else I wanted to mention; Is there a specific reason for the subtractTimes helper, rather than an operator overload in the Time class?

There are a couple of reasons for this:
- A complete and useful set of overloads would be quite complex I think, once you get into the details.
- It's a bit inefficient to do maths with these time classes directly compared to converting to `boost::rational`, because rationals are always stored normalised.

It therefore makes sense to push people to use boost::rational if they want to do anything with the times.

That said, the logic in subtractTimes is probably useful to others, so maybe it would be worth exploring a simple set of overloads (probably just + and -)?

A related point: the `operator==` and `operator!=` overloads compare structural rather than logical equality. I can see arguments for both. Again, it gets down to the question of whether we really want to make a general purpose fractional class, or just expose what's in the ADM and let users do what they want with it.

**Comment by firthm01** [comment]
> I'd rather not do this though because not all fractions can be represented as nanoseconds, so it's best if users are nudged to do the right thing.
I agree. I think maintaining the current method would tempt implementers to resort to just working in chrono::nanoseconds rather than dealing with the time data properly.

Regarding the operator overloads, I have no strong preference - it was more a curiosity thing than a suggestion. I'd say using a - operator it might make it slightly more readable than calling the subtractTimes function, but it's hardly causing an issue the way it is.

**Pull request merged**
