### PR TITLE
Provide support for existing implementations

### PR DESCRIPTION
**Pull request by firthm01**
These commits are required for the EAR Production Suite

### CODE REVIEW

**Comment by firthm01** [comment]
Looks like this is all we need from the libadm side. EPS side needs a few tweaks with `adm::SphericalPosition`, but no other libadm changes needed.

**Comment by firthm01** [comment]
Closing - changed my mind. Realised this is actually only called from one place in EPS and seems overkill to involve libadm changes to do so.

**Comment by firthm01** [comment]
Reopening after discussion

**Comment by tomjnixon** [comment]
Merged, sorry for the delay...

**Comment by firthm01** [comment]
No worries, there was no rush 👍

**Pull request closed without merging**
