### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by tomjnixon**
- borrow from the EPS build:
  - everything in one file, so hopefully easier to keep in sync
  - caches dependencies
  - enable ccache

- add clang-format check

### CODE REVIEW

**Comment by tomjnixon** [comment]
currently formatting issues are hard errors, with an exclude list for bad files (needs updating, i just wanted to see what the error looks like).

- Is an error correct, or should it just be a warning?
- Perhaps we should format all files, rather than maintaining an exclusion list?

I still need to address double builds in PRs. I think this is the solution: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/13

**Comment by tomjnixon** [comment]
> - Is an error correct, or should it just be a warning?
looks like warnings don't appear in the PR view

Also, the ccache key needs to include all the matrix parameters.

**Comment by tomjnixon** [comment]
I think this is done. I've left the formatting exclusion list in for now, as removing it would make merging 2076-2 really painful. 

Here's how a format check failure looks: https://github.com/ebu/libadm/runs/2654786779

**Comment by tomjnixon** [comment]
... actually, coverage is broken:
https://github.com/ebu/libadm/pull/106/checks?check_run_id=2654952656#step:17:294

**Comment by tomjnixon** [comment]
Got codecov working, reporting spurious changes like normal. It wasn't obvious how to configure it for builds outside of the source directory.

**Review by rsjtaylor — APPROVED** [review]

**Comment by rsjtaylor** [comment]
Looks good to me. Maybe we should add an issue to apply formatting to all the 'bad' files as a single commit once 2076-2 has been merged.

**Comment by tomjnixon** [comment]
Great, thanks.

> Maybe we should add an issue to apply formatting to all the 'bad' files as a single commit once 2076-2 has been merged.

Yeah, that was what I was thinking.

**Comment by tomjnixon** [comment]
merged, thanks!

**Pull request closed without merging**
